Repository Codewave-Crew/Lets-Do-Code, pull requests merged in 2022-10, with the labels that each got.

#17 Hello World R Language
  R/hello_world.R
Labels: hacktoberfest, hello world, hacktoberfest2022

#19 Python Keyboard Input
  Python/keyboard_input.py
Labels: hacktoberfest, hacktoberfest2022, keyboard input

#20 Java & Dart Keyboard Input
  Dart/keyboard_input.dart
  Java/KeyboardInput.java
Labels: hacktoberfest, hacktoberfest2022, keyboard input

#21 C# & C++ Keyboard Input
  C#/KeyboardInput.cs
  C++/KeyboardInput.cpp
Labels: hacktoberfest, hacktoberfest2022, keyboard input

#22 Send Email in Go
  Golang/send-email.go
Labels: hacktoberfest, hacktoberfest2022

#23 Read CSV in Go
  Golang/read_csv.go
Labels: hacktoberfest, hacktoberfest2022

#24 C & Ruby Keyboard Input
  C/KeyboardInput.c
  Ruby/keyboard_input.rb
Labels: hacktoberfest, hacktoberfest2022, keyboard input

#25 BST in Java
  Java/printDiagonal.java
Labels: hacktoberfest, iteration, hacktoberfest2022

#28 Gale Shapley Algorithm in Java
  Java/GayleShapleyAlgorithm.java
Labels: hacktoberfest, hacktoberfest2022, algorithm

#29 Keyboard Input in Go & Hello world in Pascal
  Golang/keyboard_input.go
  Pascal/main.pas
Labels: hacktoberfest, hello world, hacktoberfest2022, keyboard input

#35 Hello World in a Loop Using C++
  C++/ForLoop.cpp
Labels: hacktoberfest, hello world, iteration, hacktoberfest2022

#30 Array reduce in JavaScript
  JavaScript/reduce.js
Labels: hacktoberfest, hacktoberfest2022

#31 Christmas tree star pattern in JavaScript
  JavaScript/print-christmas-tree.js
Labels: hacktoberfest, iteration, hacktoberfest2022

#32 Array element shuffle in JavaScript
  JavaScript/shuffle-elem-array.js
Labels: hacktoberfest, hacktoberfest2022

#33 Fibonacci in JavaScript
  JavaScript/fibonacci.js
Labels: hacktoberfest, hacktoberfest2022, algorithm

#39 Do While Loop in C++
  C++/DoWhile.cpp
Labels: hacktoberfest, iteration, hacktoberfest2022

#41 Fibonacci algorithm in Java
  Java/Fibonacci.java
Labels: hacktoberfest, hacktoberfest2022, algorithm

#38 Fibonacci Series in Java & C++
  C++/Fibonacci_series.cpp
  Java/Fibonacci_series.java
Labels: hacktoberfest, hacktoberfest2022, algorithm

#43 Reverse number array in C++
  C++/Reverse.cpp
Labels: hacktoberfest, iteration, hacktoberfest2022

#50 Fibonacci algorithm in C#
  C#/Fibonnacci.cs
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#48 Added Bubble Sort (C++)
  C++/BubbleSort.cpp
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#51 Hello world in HTML
  HTML/Hello.html
Labels: hacktoberfest, hello world, hacktoberfest2022, hacktoberfest-accepted

#62 Date and time in C
  C/TimeDate.c
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#63 BogoSort algorithm in Java
  Java/BogoSort.java
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#65 BogoSort in C++
  C++/BogoSort.cpp
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#59 Bubble Sort in java & Fibonacci in Python
  Java/BubbleSort.java
  Python/fibonacci.py
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#49 Bubble sort algorithm in JavaScript
  JavaScript/bubbleSort.js
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#56 Fibonacci series in C
  C/fibo.c
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#57 Bubble sort in C
  C/bubble_sort.c
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#66 Text matching in C
  C/textmatching_.c
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#69 BogoSort algorithm in Python
  Python/bogoSort.py
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#67 Bubble Sort in C++
  C++/BubbleSort/BubbleSort.cpp
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#89 Zero to ten in numerical and text using a loop in Go Lang
  Golang/numbers.go
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#60 Factorial in JS
  JavaScript/factorial.js
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#64 BogoSort in C++
  C++/bogosort.cpp
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#68 Bubble Sort in Python
  Python/Bubble_Sort.py
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#79 Merge sort in C++
  C++/Merge sort in C++
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#80 Breadth First Search and Merge Sort in C++
  .DS_Store
  C++/BreadthFirstSearch
  C++/BreadthFirstSearch.cpp
  C++/MergeSort
  C++/MergeSort.cpp
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#81 Merge Sort in Python
  Python/Merge_sort.py
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#83 Substring Comparison in Java
  Java/Substring_Comparisons.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#82 Bubble Sort in java
  BubbleSort.java
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#85 Depth First Search with TNode in Java
  Java/DFS/TNode.java
  Java/DFS/depthFirstSearch.java
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#86 Depth first search with Preorder, In order, Post order Replace prints in Java
  Java/DepthFirstSearch.java
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#87 Merge sort in JavaScript
  JavaScript/mergeSort.js
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#91 Insertion Sort in C++
  C++/InsertionSort.cpp
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#92 String in Dart
  Dart/String.dart
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#93 Merge Sort in Java
  Java/MergeSort.java
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#94 Naive Search Algorithm in Java
  Java/NaiveSearch.java
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#95 Binary search in Python
  Python/binary_search.py
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#96 Radix Sort in Java
  Java/Radixsort.java
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#97 Leaping Frog in Java
  Java/LeapingFrog.java
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#36 Lowest Common Ancestor - BST in C++
  C++/LowestCommonAncestorBST.cpp
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#100 Boyer Moore in C
  Boyer_Moore.c
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#101 BucketSort in java
  Java/BucketSort.java
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#102 Merge Sort in C
  C/Merge-Sort.c
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#103 Merge Sort in C#
  C#/MergeSort.cs
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#104 Kadane Algorithm in C++
  C++/Kadane-Algo.cpp
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#105 ATM_Project in C++
  C++/ATM_Project.cpp
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#106 Fibonacci Serise in C
  FibonacciSeries.c
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#107 Hamming Code in C++
  C++/HammingCode.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#108 Dijkstra in Python
  Python/dijkstra.py
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#109 Sample Programs in C++
  C++/Binary_search.cpp
  C++/RemoveNthNodeFromTheEndOfList.cpp
  C++/RemoveWordsInAString.cpp
  C++/RotateTheArray.cpp
  C/Binary_Search.c
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#110 Insertion Sort in C++
  C++/Insertion_sort_Algorithm.cpp
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#111 Heap Sort in C++
  C++/Heap_Sort_Algorithm.cpp
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#112 Bucket Sort in Java
  Java/Bucket_Sort_Algorithm.java
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#113 Naive Search in C++
  C++/Naive_search_algorithm.cpp
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#115 Linked List in Python
  Python/Data Structures/linked_list.py
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#116 TicTacToe in Java
  Java/TicTacToe.java
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#117 Llinear search in C++
  C++/linear_search.cpp
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#118 Heap Sort in C
  C/heap_sort.c
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#119 Quick Sort in C++
  C++/QuickSort.cpp
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#120 Plaindrome Program in C++
  C++/Plaindrome_Program.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#121 Heap Sort in C++
  C++/heap_sort.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#122 Bogo Sort in C
  C/bogosort.c
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#123 Sum of 2 Integer in Ruby
  Ruby/add_two_integer.rb
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#124 Sample constant file in Dart
  Dart/constants.dart
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#125 KTH-SMALLEST-ELEMENT in C++
  C++/kth-smallest-element.cpp
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#126 Fibonacci Series in C
  C/FibonacciSeries.c
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#127 Kadane's Algorithm in C++
  C++/kadanesAlgorithm.cpp
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#128 Added BucketSort.cpp
  C++/BucketSort.cpp
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#129 Short trick to count digits in a number
  Python/Count_digits.py
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#130 Create Simple_Calculator.cpp
  C++/Simple_Calculator.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#131 Create Tower_of_Hanoi.cpp
  C++/Tower_of_Hanoi.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#132 add java arrayList and JS arrayChecker
  Java/arrayList/Fruites.java
  JavaScript/arrayChecker.js
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#140 Insertion Sort in C
  C/Insertion Sort.c
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#142 Selection sort in c++
  C++/selection.cpp
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#143 Insertion Sort Algorithm in Java
  Java/InsertionSort/InsertionSort.java
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#144 Shell Sort in C
  C/Shell_sort.c
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#145 Linear search in C
  C/linear_search.c
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#147 Linear Search in Java
  Java/InsertionSort.class
  Java/InsertionSort.java
  Java/LinearSearch.class
  Java/LinearSearch.java
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#152 Selection Sort in Python
  Python/selectionSort.py
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#153 Implemented quickSort
  Python/quickSort.py
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#154 Radix Sort in C++
  C++/Pigeonhole_Sort.cpp
  C++/Radix_sort.cpp
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#155 Selection Sort in C
  C/kruskalsAlgorithmMST.c
  C/primsAlgorithmMST.c
  C/quickSort.c
  C/selectionSort.c
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#156 Linear Search in C++
  C++/RecursiveLinearSearch/recursiveLinearSearch.cpp
  C++/RecursiveLinearSearch/recursiveLinearSearch.exe
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#160 Heap sort using python
  Heap_Sort.py
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#163 N Queen infinity in Java
  Java/NQueen/NQueen.java
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#165 Basic Segment Tree using C#
  C#/SegementTree.cs
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#166 add implementation for BinSort in Java
  Java/BinSort.java
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#167 BinSort in JavaScript
  JavaScript/binSort.js
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#168 BucketSort in C
  C/BucketSort.c
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#169 Fibonacci Series and sum in C++
  C++/FibonacciSeries.cpp
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#170 Bubble Sort in C++
  C++/OptimizeBubbleSort/optimizeBubbleSort.cpp
  C++/OptimizeBubbleSort/optimizeBubbleSort.exe
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#171 Linear search in C++
  Linear_search/linear_search
  Linear_search/linear_search.cpp
  linear/linear
  linear/linear.cpp
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#172 Quick select in C++
  C++/Quickselect.cpp
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#173 Fibonacci Series in Python
  Python/FibonacciSeries.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#174 Selection sort in C
  C/easy_select_sort_implement.c
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#176 Longest Common Prefix in Python
  Python/Leetcode/LongestCommonPrefix.py
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#177 Binary to Decimal in C
  C/Binary_to_decimal.c
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#178 Singleton Design Pattern in Java
  C/primefactor.exe
  Java/design-patterns/singleton/EagerInitializedSingleton.java
  Java/design-patterns/singleton/LazyInitializedSingleton.java
  Java/design-patterns/singleton/StaticBlockSingleton.java
  Java/design-patterns/singleton/ThreadSafeSingleton.java
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#179 Tower of Hanoi in C
  C/Tower_of_Hanoi.c
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#180 Bubble Sort in C#
  C#/Bubble_sort.cs
Labels: hacktoberfest, hacktoberfest2022, algorithm, hacktoberfest-accepted

#181 Roots of equation in C++
  C++/roots_of_equation.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#182 Quick Sort in Golang
  Golang/Quicksort.go
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#183 Fibonacci series in Golang
  Golang/Fibonacci.go
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#184 Disarium Number in C++
  C++/DisariusNum.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#185 Abstract Factory and Prototype Design Patterns in Java
  Java/design-patterns/abstractfactory/Abstract-Factory-Pattern.png
  Java/design-patterns/abstractfactory/Computer.java
  Java/design-patterns/abstractfactory/ComputerAbstractFactory.java
  Java/design-patterns/abstractfactory/ComputerFactory.java
  Java/design-patterns/abstractfactory/PC.java
  Java/design-patterns/abstractfactory/PCFactory.java
  Java/design-patterns/abstractfactory/README.md
  Java/design-patterns/abstractfactory/Server.java
  Java/design-patterns/abstractfactory/ServerFactory.java
  Java/design-patterns/abstractfactory/TestDesignPatterns.java
  Java/design-patterns/prototype/Employees.java
  Java/design-patterns/prototype/PrototypePatternTest.java
  Java/design-patterns/prototype/README.md
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#186 Binary Search algorithm in Elixir
  Elixir/binary_search.ex
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#187 Bubble Sort algorithm in Elixir
  Elixir/bubble_sort.ex
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#188 Fibonacci with memorization in Elixir
  Elixir/fibonacci_memoization.ex
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#189 Fibonacci algorithm in Elixir
  Elixir/fibonacci.ex
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#190 0-1 Knapsack in C++
  C++/0-1_Knapsack.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted

#191 Factorial and Count Digit in C++
  C++/Factorial.cpp
  C++/countdigits.cpp
Labels: hacktoberfest, hacktoberfest2022, hacktoberfest-accepted
