Repository Codewave-Crew/Lets-Do-Code, pull requests merged in 2023-10, with the labels that each got.

#199 Implmeneted selection sort algorithm using javascript
  JavaScript/SelectionSort.js
Labels: hacktoberfest, algorithm, hacktoberfest-accepted, hacktoberfest2023

#198 N-Queens in C++
  C++/N-Queens.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#202 Depth First Search in python
  Python/depth_first_search.py
Labels: hacktoberfest, algorithm, hacktoberfest-accepted, hacktoberfest2023

#200 Sieve of eratosthenes in C++
  C++/seive_of_eratosthenes.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#204 Quick sort algorithm in JavaScript
  JavaScript/quickSort.js
Labels: hacktoberfest, algorithm, hacktoberfest-accepted, hacktoberfest2023

#203 Djikstras algorithm and Topological sorting algorithm in C++
  C++/Dijkstra.cpp
  C++/TopologicalSort.cpp
Labels: hacktoberfest, algorithm, hacktoberfest-accepted, hacktoberfest2023

#205 Linea search algorithm in JavaScript
  JavaScript/lineaSearch.js
Labels: hacktoberfest, algorithm, hacktoberfest-accepted, hacktoberfest2023

#206 Iterative in C
  C/Iterative.c
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#208 Prime factor problem using JavaScript
  JavaScript/primeFactor.js
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#207 Best First Search in python
  Python/best_first_search.py
Labels: hacktoberfest, algorithm, hacktoberfest-accepted, hacktoberfest2023

#197 If Else in Dart
  Dart/05ifelse.dart
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#209 Radix sort algorithm in python
  Python/radix_sort.py
Labels: hacktoberfest, algorithm, hacktoberfest-accepted, hacktoberfest2023

#211 Radix sort in C#
  C#/Radixsort.cs
Labels: hacktoberfest, algorithm, hacktoberfest-accepted, hacktoberfest2023

#214 Selection Sort in Java
  Java/SelectionSort.java
Labels: hacktoberfest, algorithm, hacktoberfest-accepted, hacktoberfest2023

#212 Rust Programming Language
  Rust/Fibbonacci.rs
  Rust/HelloWorld/main.rs
  Rust/keyboard_inpit.rs
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#210 Rock Paper Scissors Game using Python
  Python/RockPaperScissorsGame.py
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#213 Distinct Subsequences in C++
  C++/distinctSubsequences.cpp
Labels: hacktoberfest, algorithm, hacktoberfest-accepted, hacktoberfest2023

#215 Odd Numbers
  Golang/oddNumbers.go
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#217 Prime Numbers
  Golang/evenNumbers.go
  JavaScript/primeNumbers.js
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#218 For Loop in Dart
  Dart/ForLoop.dart
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#224 Radix Sort algorithm in Js
  JavaScript/quickSelect.js
  JavaScript/radixSort.js
Labels: hacktoberfest, algorithm, hacktoberfest-accepted, hacktoberfest2023

#223 Binary search algorithm in C#
  C#/Binary_search.cs
Labels: hacktoberfest, algorithm, hacktoberfest-accepted, hacktoberfest2023

#225 Pigeonhole algorithm in javascript
  JavaScript/pigeonholeSort.js
Labels: hacktoberfest, algorithm, hacktoberfest-accepted, hacktoberfest2023

#221 Binary Search Recursion in C++
  C++/Binary_Search_recursion.cpp
Labels: hacktoberfest, algorithm, hacktoberfest-accepted, hacktoberfest2023

#220 Radix Sort in JS & C
  C/RadixSort.c
  JavaScript/RadixSort.js
Labels: hacktoberfest, algorithm, hacktoberfest-accepted, hacktoberfest2023

#219 Switch Case in Dart
  Dart/SwitchCase.dart
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#222 Is Graph Bipartite problem using C++
  C++/801-is-graph-bipartite.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2023

#236 Kadanes Algorithm in Python
  JavaScript/radixSortAlgo.js
  Python/kadanesAlgorithm.py
Labels: hacktoberfest, algorithm, hacktoberfest-accepted, hacktoberfest2023

#226 Update Merge Sort in Java
  Java/MergeSort/MergeSort.java
Labels: hacktoberfest, algorithm, hacktoberfest-accepted, hacktoberfest2023

#227 Heap Sort in Java
  Java/HeapSort.java
Labels: hacktoberfest, algorithm, hacktoberfest-accepted, hacktoberfest2023
